### ISSUE TITLE
SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#1093]
https://sentry.io/mapzen/datastore-prod/issues/274745567/

```
SystemStackError: stack level too deep
  app/services/geometry.rb:154:in `each'
    next if stop_index != 0 && index == start_seg_index && !previous_match_candidates.nil? && (locator_and_cost[0].distance_on_segment < previous_match_candidates.detect{|lc,i| start_seg_index == i}[0][0].distance_on_segment)
  app/services/geometry.rb:154:in `detect'
    next if stop_index != 0 && index == start_seg_index && !previous_match_candidates.nil? && (locator_and_cost[0].distance_on_segment < previous_match_candidates.detect{|lc,i| start_seg_index == i}[0][0].distance_on_segment)
  app/services/geometry.rb:154:in `block in matching_segments'
    next if stop_index != 0 && index == start_seg_index && !previous_match_candidates.nil? && (locator_and_cost[0].distance_on_segment < previous_match_candidates.detect{|lc,i| start_seg_index == i}[0][0].distance_on_segment)
  app/services/geometry.rb:149:in `each'
    @stop_segment_matching_candidates[stop_index].sort_by{|locator_and_cost,index| locator_and_cost[1] }.each do |locator_and_cost,index|
  app/services/geometry.rb:149:in `matching_segments'
    @stop_segment_matching_candidates[stop_index].sort_by{|locator_and_cost,index| locator_and_cost[1] }.each do |locator_and_cost,index|
...
(1869 additional frame(s) were not displayed)

SystemStackError: stack level too deep
```

**Comment by drewda** [comment]
Happened on import of:
- https://transit.land/dispatcher/feed-versions/fc34417b0f18633e5aad1d656af3a8e4e6fcfc60
