### ISSUE TITLE
geometry nil value

### ISSUE THREAD

**Issue by doublestranded** [transitland/transitland-datastore#636]
Probably related to #600

NoMethodError: undefined method `[]' for nil:NilClass
  from app/models/route_stop_pattern.rb:285:in `evaluate_geometry'
  from app/models/route_stop_pattern.rb:330:in `create_from_gtfs'
  from app/services/gtfs_graph.rb:301:in `block in load_tl_route_stop_patterns'
  from gtfs/source.rb:280:in `block in trip_stop_times'
  from gtfs/source.rb:276:in `each'
  from gtfs/source.rb:276:in `trip_stop_times'
  from app/services/gtfs_graph.rb:290:in `load_tl_route_stop_patterns'
  from app/services/gtfs_graph.rb:34:in `create_change_osr'
  from app/workers/feed_eater_worker.rb:46:in `perform'
  from sidekiq/processor.rb:152:in `execute_job'
  from sidekiq/processor.rb:134:in `block (2 levels) in process'
  from sidekiq/middleware/chain.rb:128:in `block in invoke'
  from sidekiq_unique_jobs/lock/until_and_while_executing.rb:8:in `block in execute'
  from sidekiq_unique_jobs/lock/while_executing.rb:19:in `synchronize'
  from sidekiq_unique_jobs/lock/until_and_while_executing.rb:6:in `execute'
  from sidekiq_unique_jobs/server/middleware.rb:16:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/server/active_record.rb:6:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/server/retry_jobs.rb:74:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/server/logging.rb:11:in `block in call'
  from sidekiq/logging.rb:32:in `with_context'
  from sidekiq/middleware/server/logging.rb:7:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/chain.rb:133:in `call'
  from sidekiq/middleware/chain.rb:133:in `invoke'
  from sidekiq/processor.rb:129:in `block in process'
  from sidekiq/processor.rb:168:in `stats'
  from sidekiq/processor.rb:128:in `process'
  from sidekiq/processor.rb:80:in `process_one'
  from sidekiq/processor.rb:68:in `run'
  from sidekiq/util.rb:17:in `watchdog'
  from sidekiq/util.rb:25:in `block in safe_thread'

**Comment by doublestranded** [comment]
Actually, this is not related to #600, but a solution requires consideration of #600. 

This problem is being triggered by a trip in SEPTA's feed with only 1 point in the corresponding shape. Rgeo returns nil from linestring generation if there is only 1 point in the input array. I did not consider this in my initial assumptions.
