### ISSUE TITLE
Import: "Undefined method 'factory'"

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#831]
Feed: https://transit.land/dispatcher/feeds/f-u0j-trenitalia (and others)
See: https://github.com/transitland/transitland/issues/154

```
{:exception_log=>"\nundefined method `factory' for nil:NilClass\n[\"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/rgeo-0.5.3/lib/rgeo/feature/types.rb:163:in `cast'\", \"/www/transitland/releases/20161014212713/app/models/concerns/has_a_geographic_geometry.rb:61:in `geometry'\", \"/www/transitland/releases/20161014212713/app/models/concerns/has_a_geographic_geometry.rb:18:in `block in convex_hull'\", \"/www/transitland/releases/20161014212713/app/models/concerns/has_a_geographic_geometry.rb:18:in `map'\", \"/www/transitland/releases/20161014212713/app/models/concerns/has_a_geographic_geometry.rb:18:in `convex_hull'\", \"/www/transitland/releases/20161014212713/app/services/gtfs_graph.rb:373:in `block in load_tl_operators'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'\", \"/www/transitland/releases/20161014212713/app/services/gtfs_graph.rb:354:in `load_tl_operators'\", \"/www/transitland/releases/20161014212713/app/services/gtfs_graph.rb:80:in `create_change_osr'\", \"/www/transitland/releases/20161014212713/app/workers/feed_eater_worker.rb:47:in `perform'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/processor.rb:155:in 
....
```

**Comment by drewda** [comment]
https://sentry.io/mapzen/datastore-prod/issues/160711875/
