### ISSUE TITLE
NoMethodError: undefined method `match' for #<Array:0x007f6712bd9888>

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#850]
https://sentry.io/mapzen/datastore-prod/issues/170447206/

```
ArgumentError: invalid date
  app/services/feed_fetcher_service.rb:114:in `read_gtfs_info'
    start_date, end_date = gtfs.service_period_range
  app/services/feed_fetcher_service.rb:107:in `fetch_and_normalize_feed_version'
    data = data.merge!(read_gtfs_info(gtfs))
  app/services/feed_fetcher_service.rb:42:in `fetch_and_return_feed_version'
    feed_version = fetch_and_normalize_feed_version(feed)
  app/workers/feed_fetcher_worker.rb:11:in `perform'
    feed_version = FeedFetcherService.fetch_and_return_feed_version(feed)
...
(38 additional frame(s) were not displayed)

NoMethodError: undefined method `match' for #<Array:0x007f6712bd9888>
Did you mean?  catch
  app/workers/feed_fetcher_worker.rb:21:in `rescue in perform'
    logger.error e.backtrace
  app/workers/feed_fetcher_worker.rb:8:in `perform'
    begin
...
(28 additional frame(s) were not displayed)

NoMethodError: undefined method `match' for #<Array:0x007f6712bd9888>
Did you mean?  catch
```

**Comment by drewda** [comment]
https://sentry.io/mapzen/datastore-prod/issues/175000852/

**Comment by irees** [comment]
This turns out to be two errors:
- invalid date in calendar_dates.txt
- error in logging method

#823 resolves the first, then I'll add a fix in `gtfs` gem to resolve second.
