### ISSUE TITLE
TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#905]
https://sentry.io/mapzen/datastore-prod/issues/195808529/

```
TypeError: no implicit conversion of nil into String
  app/services/feed_fetcher_service.rb:151:in `read_gtfs_info'
    start_date, end_date = gtfs.service_period_range
  app/services/feed_fetcher_service.rb:144:in `fetch_and_normalize_feed_version'
    data = data.merge!(read_gtfs_info(gtfs))
  app/services/feed_fetcher_service.rb:54:in `fetch_and_return_feed_version'
    feed_version = fetch_and_normalize_feed_version(feed)
  app/workers/feed_fetcher_worker.rb:11:in `perform'
    feed_version = FeedFetcherService.fetch_and_return_feed_version(feed)
...
(36 additional frame(s) were not displayed)

TypeError: no implicit conversion of nil into String
```

**Comment by drewda** [comment]
https://sentry.io/mapzen/datastore-prod/issues/298654569/

**Comment by drewda** [comment]
https://sentry.io/mapzen/datastore-prod/issues/246861557/

**Comment by drewda** [comment]
One instance of this happening:

- Dispatcher: https://transit.land/dispatcher/feeds/f-9y68-clevelandarearapidtransitcart
- remote feed URL: http://www.cartgps.com/gtfs

The zip file that is currently served includes many empty files:

![screen shot 2017-08-02 at 4 30 09 pm](https://user-images.githubusercontent.com/212369/28899440-e98a8858-779f-11e7-9f86-8637ee48f2fc.png)

I've just contacted CART to see if they have a current GTFS feed at a new location. 

We may also want to consider throwing a more descriptive error about missing calendars in the future -- as well as catching it more gracefully, so it doesn't have to go all the way to Sentry.
