### ISSUE TITLE
Couldn't find stops in quality checks

### ISSUE THREAD

**Issue by doublestranded** [transitland/transitland-datastore#941]
Changeset::Error: Changeset::Error Couldn't find Stop

Feed: f-9vk-metropolitantransitauthorityofharriscounty

**Comment by doublestranded** [comment]
{:exception_log=>"\nChangeset::Error Couldn't find Stop\n[\"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/core.rb:196:in `find_by!'\", \"/www/transitland/releases/20170125205759/app/models/concerns/has_a_onestop_id.rb:10:in `find_by_onestop_id!'\", \"/www/transitland/releases/20170125205759/app/services/quality_check.rb:183:in `distances_between_rsp_stops'\", \"/www/transitland/releases/20170125205759/app/services/quality_check.rb:147:in `block (2 levels) in check'\", \"/www/transitland/releases/20170125205759/app/services/quality_check.rb:146:in `each_index'\", \"/www/transitland/releases/20170125205759/app/services/quality_check.rb:146:in `block in check'\", \"/usr/local/lib/ruby/2.3.0/set.rb:306:in `each_key'\", \"/usr/local/lib/ruby/2.3.0/set.rb:306:in `each'\", \"/www/transitland/releases/20170125205759/app/services/quality_check.rb:142:in `check'\", \"/www/transitland/releases/20170125205759/app/models/changeset.rb:175:in `check_quality'\", \"/www/transitland/releases/20170125205759/app/models/changeset.rb:301:in `block in apply!'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'\", \"/www/transitland/releases/20170125205759/app/models/changeset.rb:282:in `apply!'\", \"/www/transitland/releases/20170125205759/app/services/gtfs_graph.rb:151:in `create_change_osr'\", \"/www/transitland/releases/20170125205759/app/workers/feed_eater_worker.rb:30:in `perform'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:158:in `execute_job'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/active_record.rb:6:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:8:in `block in execute'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/lock/while_executing.rb:19:in `synchronize'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:6:in `execute'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/server/middleware.rb:16:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/logging.rb:32:in `with_context'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:7:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:174:in `stats'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:131:in `block in process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:126:in `process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:82:in `process_one'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:70:in `run'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:17:in `watchdog'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'\"]\n"}

**Comment by doublestranded** [comment]
Most recent feed version imported successfully.
